import { ModuleConfig } from "@/types/admin.types";

export const BRAND_MODULES: ModuleConfig[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    path: "/brand/dashboard",
    icon: "Squares2X2Icon",
    adminTypes: ["brand"],
  },
  {
    id: "team",
    name: "Team",
    path: "/brand/team",
    icon: "UsersIcon",
    adminTypes: ["brand"],
    children: [
      {
        id: "users",
        name: "Users",
        path: "/brand/team/user",
        icon: "UserIcon",
        adminTypes: ["brand"],
      },
      {
        id: "roles",
        name: "Roles",
        path: "/brand/team/role",
        icon: "ShieldCheckIcon",
        adminTypes: ["brand"],
      },
    ],
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    path: "/brand/whatsapp",
    icon: "ChatBubbleLeftRightIcon",
    adminTypes: ["brand"],
  },
  {
    id: "templates",
    name: "Templates",
    path: "/brand/templates",
    icon: "DocumentTextIcon",
    adminTypes: ["brand"],
  },
  {
    id: "webhooks",
    name: "Webhooks",
    path: "/brand/webhooks",
    icon: "ArrowsRightLeftIcon",
    adminTypes: ["brand"],
  },
  {
    id: "billing",
    name: "Billing",
    path: "/brand/billing",
    icon: "CreditCardIcon",
    adminTypes: ["brand"],
  },
  {
    id: "compliance",
    name: "Compliance",
    path: "/brand/compliance",
    icon: "DocumentCheckIcon",
    adminTypes: ["brand"],
  },
  {
    id: "settings",
    name: "Settings",
    path: "/brand/settings",
    icon: "Cog6ToothIcon",
    adminTypes: ["brand"],
  },
  {
    id: "danger-zone",
    name: "Danger Zone",
    path: "/brand/danger-zone",
    icon: "ExclamationTriangleIcon",
    adminTypes: ["brand"],
  },
  {
    id: "notifications",
    name: "Notifications",
    path: "/brand/notifications",
    icon: "BellIcon",
    adminTypes: ["brand"],
  },
];

export const AGENCY_MODULES: ModuleConfig[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    path: "/agency/dashboard",
    icon: "Squares2X2Icon",
    adminTypes: ["agency"],
  },
  {
    id: "brands",
    name: "Brands",
    path: "/agency/brands",
    icon: "BuildingOfficeIcon",
    adminTypes: ["agency"],
  },
  {
    id: "team",
    name: "Team",
    path: "/agency/team",
    icon: "UsersIcon",
    adminTypes: ["agency"],
    children: [
      {
        id: "users",
        name: "Users",
        path: "/agency/team/user",
        icon: "UserIcon",
        adminTypes: ["agency"],
      },
      {
        id: "roles",
        name: "Roles",
        path: "/agency/team/role",
        icon: "ShieldCheckIcon",
        adminTypes: ["agency"],
      },
    ],
  },
  {
    id: "billing",
    name: "Billing",
    path: "/agency/billing",
    icon: "CreditCardIcon",
    adminTypes: ["agency"],
  },
  {
    id: "whitelabel",
    name: "Whitelabel",
    path: "/agency/whitelabel",
    icon: "SwatchIcon",
    adminTypes: ["agency"],
  },
  {
    id: "reports",
    name: "Reports",
    path: "/agency/reports",
    icon: "ChartBarIcon",
    adminTypes: ["agency"],
  },
  {
    id: "templates",
    name: "Templates",
    path: "/agency/templates",
    icon: "DocumentTextIcon",
    adminTypes: ["agency"],
  },
  {
    id: "compliance",
    name: "Compliance",
    path: "/agency/compliance",
    icon: "DocumentCheckIcon",
    adminTypes: ["agency"],
  },
  {
    id: "settings",
    name: "Settings",
    path: "/agency/settings",
    icon: "Cog6ToothIcon",
    adminTypes: ["agency"],
  },
  {
    id: "danger-zone",
    name: "Danger Zone",
    path: "/agency/danger-zone",
    icon: "ExclamationTriangleIcon",
    adminTypes: ["agency"],
  },
];

export const OWNER_MODULES: ModuleConfig[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    path: "/owner/dashboard",
    icon: "Squares2X2Icon",
    adminTypes: ["owner"],
  },
  {
    id: "team",
    name: "Team",
    path: "/owner/team",
    icon: "UsersIcon",
    adminTypes: ["owner"],
    children: [
      {
        id: "users",
        name: "Users",
        path: "/owner/team/user",
        icon: "UserIcon",
        adminTypes: ["owner"],
      },
      {
        id: "roles",
        name: "Roles",
        path: "/owner/team/role",
        icon: "ShieldCheckIcon",
        adminTypes: ["owner"],
      },
    ],
  },
  {
    id: "agencies",
    name: "Agencies",
    path: "/owner/agencies",
    icon: "BriefcaseIcon",
    adminTypes: ["owner"],
  },
  {
    id: "brands",
    name: "Brands",
    path: "/owner/brands",
    icon: "BuildingOfficeIcon",
    adminTypes: ["owner"],
  },
  {
    id: "billing",
    name: "Billing",
    path: "/owner/billing",
    icon: "CreditCardIcon",
    adminTypes: ["owner"],
  },
  {
    id: "subscription",
    name: "Subscription",
    path: "/owner/subscription",
    icon: "CalendarIcon",
    adminTypes: ["owner"],
  },
  {
    id: "coupon",
    name: "Coupon",
    path: "/owner/coupon",
    icon: "TicketIcon",
    adminTypes: ["owner"],
  },
  {
    id: "faq",
    name: "FAQ",
    path: "/owner/faq",
    icon: "QuestionMarkCircleIcon",
    adminTypes: ["owner"],
  },
  {
    id: "master",
    name: "Master Data",
    path: "/owner/master",
    icon: "ServerIcon",
    adminTypes: ["owner"],
  },
  {
    id: "features",
    name: "Features",
    path: "/owner/features",
    icon: "BoltIcon",
    adminTypes: ["owner"],
  },
  {
    id: "monitoring",
    name: "Monitoring",
    path: "/owner/monitoring",
    icon: "ChartBarIcon",
    adminTypes: ["owner"],
  },
  {
    id: "logs",
    name: "Logs",
    path: "/owner/logs",
    icon: "DocumentTextIcon",
    adminTypes: ["owner"],
  },
  {
    id: "config",
    name: "Config",
    path: "/owner/config",
    icon: "Cog6ToothIcon",
    adminTypes: ["owner"],
  },
  {
    id: "emergency",
    name: "Emergency",
    path: "/owner/emergency",
    icon: "ExclamationTriangleIcon",
    adminTypes: ["owner"],
  },
  {
    id: "templates",
    name: "Templates",
    path: "/owner/templates",
    icon: "RectangleGroupIcon",
    adminTypes: ["owner"],
  },
];
